Added IBM Validated Solftware List function to bin/package_build
openmainframeproject/software-discovery-tool pull request #122
Opened 2023-05-16 10:44 UTC by Princee215

This is the fix for #100 @arshPratap @pleia2. Please take a look. I've added an IBM Validated Software List function in the bin/package_build.py file.

2023-05-16 10:47 UTC, arshPratap commented
Nice work @Princee215 ..seems alright to me..might have to change the way we save the files but this should do for now. I would like to know your thoughts on this @pleia2

2023-05-16 11:33 UTC, xtanion commented
Hi @Princee215 , This LGTM, one suggestion as @pleia2 mentioned
>We could add this to package_build.py but my inclination is to create a separate script that allows you to specify which distributions from the list you want to build the JSON for.
You should create it as a separate script and make the user choose which `.json` file they want to build.

2023-05-16 18:27 UTC, pleia2 commented
I think it's OK to keep it with the rest in package_build.py, but my concern is that it gets a little confusion as to how to use it.

My first concern is that "opensource" is incredibly vague, especially since everything we currently index with this tool is technically opensource :smile:  Instead, maybe the keyword should be "ibm-validated"? We also want to make sure these are put into /opt/software-discovery-tool/distro_data/data_files/ like all the other output of this script (right now it's putting them in the current directory, which may be confusing since it's different from the rest).

We also need to be clearer to the user of the tool what's happening. For example, if they follow instructions from the help for Debian, it's very clear, it's generating the data for every Debian version supported in the tool and gives you the filenames in STDOUT:

elizabeth@r2d2:~$ ./package_build.py debian
Extracting debian data ... 
Saved!
filename: Debian_Buster_List.json
Saved!
filename: Debian_Bullseye_List.json
Thanks for using SDT!

By contrast, this is what happens when you run this for "opensource":

elizabeth@r2d2:~$ ./package_build.py opensource
Extracting data for opensource ... 
Thanks for using SDT!

...What just happened? So you'll want to do something similar to the others, where it tells you what filenames it's creating as it goes through them.

The last thing is that the code is just doing a small subset of the distributions used in validated software list (@arshPratap started his work as a proof of concept), so you'll want to look at the live list and make sure you're including everything, which means the RHEL versions as well: https://www.ibm.com/community/z/open-source-software/

I'm really happy to see this coming together! It's the last step for including this in the production tool, and a lot of folks have been asking for it.

2023-05-22 19:28 UTC, Princee215 commented
Thanks @pleia2 for the suggestion, I'm trying and working out all the changes that you've asked for. I'm working on the changes and will update the PR.

2023-05-22 20:08 UTC, arshPratap commented
@Princee215  I understand some of the requested changes might be complex but fret not I and @pleia2 are around to help you and if you ever feel stuck please do ask your queries either here or on the slack channel. Thanks  !

2023-06-11 07:26 UTC, Princee215 commented
Sure @pleia2 I'll take a look into this and try to solve these issues which you pointed out.

2023-06-14 19:40 UTC, Princee215 commented
Hey, @pleia2  and @arshPratap, I've maded the changes as asked. Thanks, @xtanion for the suggestion. Instead of creating different script I've added an argument for the user to choose which IBM-Validated .json file they want to build. 

Please take a look!

2023-06-15 13:55 UTC, arshPratap reviewed
I am a bit unclear on the distro distribution here but otherwise the changes look reasonable to me.

2023-06-24 18:27 UTC, arshPratap commented
Great Work @Princee215 , just needs some rebasing ! works well for me (have attached a screenshot below for the same ). @pleia2 would like to know your thoughts on this 

![Screenshot from 2023-06-24 23-27-44](https://github.com/openmainframeproject/software-discovery-tool/assets/62841337/cdc5ee6e-0868-4a72-9ef0-10aad9236a50)

2023-06-28 18:49 UTC, pleia2 requested changes
Overall, I think it's in pretty good shape, nice work!

I noted below about the Ubuntu 20 vs 20.04 issues. We really do want to be precise and accurate here, so it's clear that we're focused on the every-other-year LTS releases, not the .10 releases (I realize the source Validated Software List is unclear in this regard since they call it Ubuntu 20.x and 22.x, but this is also a bug, and we don't need to do the same :smile: ).

As Arsh mentioned, a rebase is required too in order to get this merged.

2023-06-28 18:49 UTC, pleia2 commented on src/config/supported_distros.py
> +    'IBM Z Validated Ubuntu 22': 'IBM_Validated_OSS_List_Ubuntu_2204.json'
These should be Ubuntu 20.04 and 22.04 (the .04 is important, since there were also Ubuntu 20.10 and 22.10 releases).

2023-06-28 18:49 UTC, pleia2 commented on src/static/js/views/faq.html
> +            <li>IBM Validated List for Ubuntu 22</li>
Same as above for Ubuntu 20.04 and 22.04.

2023-06-28 18:49 UTC, pleia2 commented on bin/package_build.py
> +		if oskey == 'Ubuntu_20' or oskey == 'all':
This should be Ubuntu_2004

2023-06-28 18:49 UTC, pleia2 commented on bin/package_build.py
> +		if oskey == 'Ubuntu_22' or oskey == 'all':
Same as above, but Ubuntu_2204

2023-06-28 18:49 UTC, pleia2 commented on bin/package_build.py
> +				json.dump(ubuntu22_list,file,indent=2)
And ubuntu22.04

2023-06-28 18:49 UTC, pleia2 commented on src/config/supported_distros.py
> +    'IBM Z Validated Ubuntu 22': 'IBM_Validated_OSS_List_Ubuntu_2204.json'
And very minor, but some of the above are spaces and some are tabs, causing the file to be a bit out of whack when tabset is not 4. We've tended to use tabs, so let's stick with that.

2023-06-30 20:06 UTC, Princee215 commented
I've made the required changes asked above. Please take a look and let me know if any more changes need to be made. @pleia2

2023-06-30 20:28 UTC, pleia2 approved these changes

2023-06-30 20:28 UTC, merged