Adding Code for Debian 12
openmainframeproject/software-discovery-tool pull request #152
Opened 2023-08-16 17:53 UTC by Princee215

As Debian 12 is released, I've added code to package_build.py as stated in Issue #144 . Please take a look. @pleia2 @arshPratap

2023-08-16 18:44 UTC, arshPratap approved these changes
@Princee215 thanks for this

2023-08-16 20:17 UTC, pleia2 requested changes
This file looks great! But please also add it to /src/config/supported_distros.py and in the documentation src/static/js/views/faq.html

2023-08-18 17:31 UTC, Princee215 commented
@pleia2 I've made the asked changes. Please take a look.
Except this I've also remove the comment for fedora 38 as it available in our tracked data file now.

2023-08-18 18:07 UTC, pleia2 approved these changes

2023-08-18 18:07 UTC, merged