Edited fedora code to ignore error 404 messages, while creating fedora json files
openmainframeproject/software-discovery-tool pull request #162
Opened 2023-09-10 06:49 UTC by Princee215

While creating Fedora files through ./bin/package_build.py. We face some errors while creating these files as can be seen in Issue #148. As mentioned directories are not present for following Fedora version- 

![Screenshot from 2023-07-29 22-56-22](https://github.com/openmainframeproject/software-discovery-tool/assets/80761691/f47ad7f3-ccb7-4d06-ac12-ae3a09b56552)

- Fedora 35, 36, 37 - Directory 8
- Fedora 38 - Directory 5

So, what I did, I added continue instead of raising an error. Therefore, if some directory is not present for some distro version we'll just ignore that and iterate over to next directory. And except that I've also added 1 in dirs string as it'll cover a wider range and if some directory is not there it'll just ignore that and you won't see any errors in the terminal.

@pleia2 and @arshPratap please take a look at it.

2023-09-14 10:13 UTC, arshPratap requested changes

2023-09-14 10:13 UTC, arshPratap commented on bin/package_build.py
> -					raise Exception(f"404 Directory {dirs[each]} not found")
@Princee215 lets keep a verbose message to let users atleast know the issue they are facing

2023-09-14 10:14 UTC, arshPratap commented
@Princee215 looks good to me
@pleia2 thoughts ?

2023-09-15 07:41 UTC, arshPratap commented on bin/package_build.py
> -					raise Exception(f"404 Directory {dirs[each]} not found")
@Princee215 resolved

2023-09-15 07:48 UTC, arshPratap commented on bin/package_build.py
>  			except Exception as e:
@Princee215 let's remove this try - except block and have the try block above at [here](https://github.com/openmainframeproject/software-discovery-tool/pull/162/files#diff-6f39b12c55db3a00f6283da33cbe8fdbf0aa23ef14b767cc7ce7dec7a134654eL127)

2023-09-15 18:44 UTC, arshPratap commented
@Princee215 lgtm.. Thanks for the contributions!

2023-09-15 18:47 UTC, Princee215 commented
@pleia2, @arshPratap I've made some changes again, as discussed with Arsh, I've put the code in try catch block, and checked for a condition were we're checking if both of the links are not working. Still I've some doubts that we should output message if some directory is not present or we should ignore it? And should we put it in a try catch block too or is it fine as we're using now!

Take a look and let me know. I'll be happy to make changes.

2023-09-21 15:13 UTC, pleia2 approved these changes

2023-09-21 15:14 UTC, merged