added extra caution for SUSE users
openmainframeproject/software-discovery-tool pull request #54
Opened 2021-07-14 21:23 UTC by rachejazz

Signed-off-by: rachejazz <divyadeepti2000@gmail.com>

Tested my script recently on OpenSUSE, looks like python3 needs to be specified since it has python2 as default.
And also, there was no `/bin/python3` :'D on SUSE
Changed and added a workaround too in case of permission error.

2021-07-16 04:15 UTC, rachejazz commented
I'll update the script as well and then you can review this PR.

2021-07-17 08:29 UTC, rachejazz commented
![image](https://user-images.githubusercontent.com/42383989/126031140-fc2aec41-94c7-401a-be98-304db0724fce.png)

2021-07-19 16:23 UTC, pleia2 requested changes
Just one tiny change to the description in the config file.

2021-07-19 16:23 UTC, pleia2 commented on src/config/config.py
> +		'ClefOS Epel 7': 'ClefOS_7_List.json'
Epel is a different section of the repository :smile: (we may include it later, based on feedback from Neale) according to the script above, you want "base" here.

2021-07-19 16:23 UTC, pleia2 commented on bin/package_build.py
> +#!/usr/bin/python3
Yeah, I had to make the same change on Debian. If this works better everywhere :+1:

2021-07-19 17:39 UTC, pleia2 approved these changes
Looks good, but I'll hold off on actual merging until we hear back from Neale :+1:

2021-07-21 16:01 UTC, rachejazz commented
Should I proceed for OpenSUSE addition? Sine Nominie response might delay

2021-07-21 17:05 UTC, pleia2 commented
I'll just merge this. We can adjust later if there are problems, and we'll still wait on the data import.

2021-07-21 17:06 UTC, merged